version: '3.8'

services:
  db:
    container_name: postgres_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: library
    ports:
      - "5432:5432"

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@admin.com
      PGADMIN_DEFAULT_PASSWORD: p@ssw0rd
    ports:
      - "5050:80"

  backend:
    container_name: backend_container
    build: .
    restart: always
    command: python /app/application.py
    volumes:
      - ./app:/app
      - ./db:/db
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=/app/application.py
      - FLASK_ENV=development
      - DATABASE_URL=postgres://postgres:postgres@postgres_container:5432/library
    depends_on:
      - db
      - pgadmin
