version: '3.8'

services:
  db:
    container_name: db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: library
    ports:
      - "5432:5432"

  db_visualizer:
    container_name: db_visualizer
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@admin.com
      PGADMIN_DEFAULT_PASSWORD: p@ssw0rd
    ports:
      - "5050:80"
    depends_on:
      - db

  app:
    container_name: app
    build: app
    restart: always
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres_container:5432/library
    depends_on:
      - db
