version: '3.8'

services:
  db:
    container_name: db
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root@passowrd
      MYSQL_DATABASE: library
      MYSQL_USER: library
      MYSQL_PASSWORD: library@passowrd
      MYSQL_ROOT_HOST: '%'
    ports:
      - "6033:3306"
    # volumes:
    #   - dbdata:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 5050:80
    depends_on:
      - db

  app:
    container_name: app
    build: app
    restart: always
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    # environment:
    #   - DATABASE_URL=postgres://postgres:postgres@postgres_container:5432/library
    depends_on:
      - db

  app_ui:
    container_name: app_ui 
    build: app-ui
    restart: always
    volumes:
      - ./app-ui:/app
    ports:
      - "5173:5173" 
    stdin_open: true
    depends_on:
      - app
